name : ReleaseCI
on:
  pull_request:
    types:
      - closed
    branches: ["main"]
    paths: ["dce/**"]
jobs:
  detect-file-changes:
    runs-on: ubuntu-20.04
    # Set job outputs to values from filter step
    outputs:
      dce: ${{ steps.filter.outputs.dce }}
    steps:
      - name: Checkout dce code
        uses: actions/checkout@v1
      # For pull requests it's not necessary to checkout the code
      - name: Apply filters to check file(s) cahnges
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            dce:
              - 'dce/**'
  dce:
    needs: [detect-file-changes]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Release to S3
        env:
          AWS_S3_BUCKET: ${{secrets.AWS_Bucket_Name}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_Access_Key}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_Access_Secret}}
          AWS_DEFAULT_REGION: ${{secrets.AWS_Default_Region}}
        run: |
          
          sudo pip install awscli
          zip -r dce.zip dce/
          aws s3 cp dce.zip s3://${{secrets.AWS_Bucket_Name}}/module/
          aws s3 sync dce/scripts/ s3://${{secrets.AWS_Bucket_Name}}/scripts/
          zip -r dce_lambda.zip dce/scripts/dce_lambda.py
          aws s3 cp dce_lambda.zip s3://${{secrets.AWS_Bucket_Name}}/scripts/
